# =============================================================================
# COMPUTE LAYER OUTPUTS
# =============================================================================



# ECS
output "ecs_cluster_id" {
  description = "ID of the ECS cluster"
  value       = var.enable_ecs ? module.ecs[0].cluster_id : null
}

output "ecs_cluster_arn" {
  description = "ARN of the ECS cluster"
  value       = var.enable_ecs ? module.ecs[0].cluster_arn : null
}

output "ecs_cluster_name" {
  description = "Name of the ECS cluster"
  value       = var.enable_ecs ? module.ecs[0].cluster_name : null
}

# Lambda
output "lambda_functions" {
  description = "Map of Lambda function details"
  value       = length(var.lambda_functions) > 0 ? module.lambda[0].functions : {}
}

output "lambda_function_arns" {
  description = "Map of Lambda function ARNs"
  value       = length(var.lambda_functions) > 0 ? module.lambda[0].function_arns : {}
}

# =============================================================================
# EKS OUTPUTS
# =============================================================================

output "eks_cluster_id" {
  description = "ID of the EKS cluster"
  value       = var.enable_eks ? module.eks[0].cluster_id : null
}

output "eks_cluster_arn" {
  description = "ARN of the EKS cluster"
  value       = var.enable_eks ? module.eks[0].cluster_arn : null
}

output "eks_cluster_name" {
  description = "Name of the EKS cluster"
  value       = var.enable_eks ? module.eks[0].cluster_name : null
}

output "eks_cluster_endpoint" {
  description = "Endpoint for your Kubernetes API server"
  value       = var.enable_eks ? module.eks[0].cluster_endpoint : null
}

output "eks_cluster_version" {
  description = "The Kubernetes version for the cluster"
  value       = var.enable_eks ? module.eks[0].cluster_version : null
}

output "eks_cluster_security_group_id" {
  description = "Security group ID attached to the EKS cluster"
  value       = var.enable_eks ? module.eks[0].cluster_security_group_id : null
}

output "eks_cluster_certificate_authority_data" {
  description = "Base64 encoded certificate data required to communicate with the cluster"
  value       = var.enable_eks ? module.eks[0].cluster_certificate_authority_data : null
  sensitive   = true
}

output "eks_cluster_oidc_issuer_url" {
  description = "The URL on the EKS cluster OIDC Issuer"
  value       = var.enable_eks ? module.eks[0].cluster_oidc_issuer_url : null
}

output "eks_node_groups" {
  description = "Map of attribute maps for all EKS managed node groups created"
  value       = var.enable_eks ? module.eks[0].node_groups : {}
}

output "eks_fargate_profiles" {
  description = "Map of attribute maps for all EKS Fargate profiles created"
  value       = var.enable_eks ? module.eks[0].fargate_profiles : {}
}

output "eks_cluster_addons" {
  description = "Map of attribute maps for all EKS cluster addons enabled"
  value       = var.enable_eks ? module.eks[0].cluster_addons : {}
}

output "eks_cluster_iam_role_arn" {
  description = "IAM role ARN associated with EKS cluster"
  value       = var.enable_eks ? module.eks[0].cluster_iam_role_arn : null
}

output "eks_node_group_iam_role_arn" {
  description = "IAM role ARN associated with EKS node group"
  value       = var.enable_eks ? module.eks[0].node_group_iam_role_arn : null
}

output "eks_kubectl_config" {
  description = "kubectl config as generated by the module"
  value       = var.enable_eks ? module.eks[0].kubectl_config : null
  sensitive   = true
}

# =============================================================================
# API GATEWAY OUTPUTS
# =============================================================================

output "api_gateway_rest_api_id" {
  description = "ID of the REST API"
  value       = var.enable_api_gateway ? module.api_gateway[0].rest_api_id : null
}

output "api_gateway_rest_api_arn" {
  description = "ARN of the REST API"
  value       = var.enable_api_gateway ? module.api_gateway[0].rest_api_arn : null
}

output "api_gateway_stage_invoke_url" {
  description = "URL to invoke the API pointing to the stage"
  value       = var.enable_api_gateway ? module.api_gateway[0].stage_invoke_url : null
}

output "api_gateway_stage_arn" {
  description = "ARN of the API Gateway stage"
  value       = var.enable_api_gateway ? module.api_gateway[0].stage_arn : null
}

output "api_gateway_execution_arn" {
  description = "Execution ARN to be used in lambda_permission's source_arn"
  value       = var.enable_api_gateway ? module.api_gateway[0].rest_api_execution_arn : null
}

output "api_gateway_resources" {
  description = "Map of API Gateway resources"
  value       = var.enable_api_gateway ? module.api_gateway[0].api_resources : {}
}

output "api_gateway_methods" {
  description = "Map of API Gateway methods"
  value       = var.enable_api_gateway ? module.api_gateway[0].api_methods : {}
}

output "api_gateway_usage_plans" {
  description = "Map of API Gateway usage plans"
  value       = var.enable_api_gateway ? module.api_gateway[0].usage_plans : {}
}

output "api_gateway_api_keys" {
  description = "Map of API Gateway API keys"
  value       = var.enable_api_gateway ? module.api_gateway[0].api_keys : {}
  sensitive   = true
}

output "api_gateway_domain_name" {
  description = "Custom domain name configuration"
  value       = var.enable_api_gateway ? module.api_gateway[0].domain_name : null
}

output "api_gateway_access_log_group_arn" {
  description = "ARN of the CloudWatch log group for access logs"
  value       = var.enable_api_gateway ? module.api_gateway[0].access_log_group_arn : null
}
